/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_map_lhq_permission_demo_jni_myJNI */

#ifndef _Included_com_baidu_map_lhq_permission_demo_jni_myJNI
#define _Included_com_baidu_map_lhq_permission_demo_jni_myJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baidu_map_lhq_permission_demo_jni_myJNI
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_baidu_1map_lhq_permission_1demo_jni_myJNI_sayHello
  (JNIEnv *, jclass);
    //返回一句话
    return (*env)->NewStringUTF(env,"JNI hahahahahahahaha");
    #ifdef __cplusplus
}
#endif
#endif
